[tool.poetry]
name = "python-dao"
version = "0.1.0"
description = ""
authors = ["Maxime Boulanger <boumax84@gmail.com>"]
readme = "README.md"
packages = [{include = "python_dao"}]

[tool.poetry.dependencies]
python = "^3.11"
pre-commit = "^3.0.4"
pylint = "^2.16.2"
eradicate = "^2.1.0"
pybetter = "^0.4.1"
autotyping = "^22.9.0"
pytest = "^7.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 1


[project.urls]
"Homepage" = "https://github.com/mbml84/python-dao"
"Bug Tracker" = "https://github.com/mbml84/python-dao/issues"
